# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'gb-svc-rpt-extract-mas'
    honor_timestamps: true
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /extractor/actuator/prometheus
    scheme: http
    follow_redirects: true

    static_configs:
    - targets: ['extractor-master-cc-*-*.standardchartered.com']
      labels:
              group: 'sa-02'
              service: 'extractor'
              
  - job_name: 'gb-svc-rpt-txload-mas'
    honor_timestamps: true
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /transformer/actuator/prometheus
    scheme: http
    follow_redirects: true

    static_configs:
    - targets: ['transformer-master-cc-reporting-*-*.standardchartered.com']
      labels:
              group: 'sa-03'
              service: 'transformer'

  - job_name: 'sa05-gb-svc-rpt-extract-mas'
    honor_timestamps: true
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /extractor/actuator/prometheus
    scheme: http
    follow_redirects: true

    static_configs:
    - targets: ['gb-svc-rpt-ext-mas-cc-reporting-*-*.standardchartered.com']
      labels:
              group: 'sa-05'
              service: 'extractor'

  - job_name: 'sa05-gb-svc-rpt-txload-mas'
    honor_timestamps: true
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /transformer/actuator/prometheus
    scheme: http
    follow_redirects: true

    static_configs:
    - targets: ['gb-svc-rpt-tx-mas-cc-reporting-*-*.standardchartered.com']
      labels:
            group: 'sa-05'
            service: 'transformer'

  - job_name: 'etl'
    honor_timestamps: true
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /transformer/actuator/prometheus
    scheme: http
    follow_redirects: true
    static_configs:
    - targets: ['gb-svc-rpt-tx-mas-cc-reporting-*-*.standardchartered.com']
      labels:
            group: 'sa-05'


